
{if isset($FormData.js_libs)}
 {foreach from=$FormData.js_libs item=lib}
   {$lib}
 {/foreach}
{/if}

 <!-- The form attributes are: is it a GET or POST form, the URL to action -->
 <form {$FormData.attributes}>
   <table class="form-lg mb0" border="0" cellspacing="0" cellpadding="0">
    {if $FormData.errors|@count || isset($smarty.get.status)}
    <tr>
      <td colspan="2" class="form-warn">
       {if $FormData.errors|@count}
           <div class="warn-bx" id="warning">
              <strong>Застереження!</strong><br/>
              У формі знайдені помилки.<br/>
              {*
              <div style="text-align:left;margin-left:20px;">
                {foreach from = FormData.errors item=elem}
                  <br/>{$elem}
                {/foreach}
              </div>
              *}
           </div>
       {elseif $smarty.get.status == 'added'}
           <div class="warn-bx green" id="warning">
             <strong>Вітання!</strong><br/>
             Дані додано успішно!
           </div>
       {elseif $smarty.get.status == 'updated'}
           <div class="warn-bx green" id="warning">
             <strong>Вітання!</strong><br/>
             Дані змінено успішно!
           </div>
       {elseif $smarty.get.status == 'deleted'}
           <div class="warn-bx green" id="warning">
             <strong>Вітання!</strong><br/>
             Дані видалено успішно!
           </div>
       {/if}
     </td>
    </tr>
    {/if}
	  <!-- HEADER -->
      <tr>
        <td colspan="2">
            <h2>Крок 2<br /><small>Додати або редагувати елемент</small></h2>
        </td>
      </tr>
      <!-- HEADER -->

      <tr>
       <td colspan="2">

       {if isset($FormData.hidden)}
         {foreach from=$FormData.hidden item=head}
           {$head}
         {/foreach}
       {/if}


       {* Generate for every field in the form.
        * $FormData contains more than just form fields, this other stuff is ignored.
        * Form fields are arrays that contain the following elements of interest:
        * id      Always exists, generated by QF but can be set by the 'id' element
        *         of the 3rd argument to addElement().
        * name    This is the field name that will be used in $_GET/$_POST.
        *         This is usually the same as $key set by {foreach}, but see group below.
        * label   This some text that should be used to tell the user what the field is for,
        *         eg 'Age'. This is set by 'label' element of the 4th argument to addElement()
        *         or with the setLabel() method. It might not be set at all.
        * html    The html for the input field, you generate this.
        * type    text, image, textarea, ... If you were clever you could look at this.
        *         Note that this is not set for: fieldset or group.
        * attribs An array of field attributes, some generated by QuickForm2 others
        *         that were given to addElement().
        * error   This will be present if there is a validation error associated with this field.
        *         If the option group_errors is set this will not be generated, any error
        *         will be in a pseudo field called 'errors', this is what happens in this example.
        * value   The element value.
        * elements If a fieldset or group, the contained elements.
        *          If a checkbox an array keyed by fieldname index (eg '0' from 'vegetable[0]')
        *            value is the form field.
        *          If a radio button an array keyed by the field 'value' (the 'value' from the attributes)
        *            value is the form field.
        *
        * Often you will generate the fields in the form and place them where you want them,
        * to do this use the fields, eg: {$FormData.Age.html}
        *
        * What is going on here is complicated because it searches $FormData, it ignores anything
        * that is not an input field (is_array($Field) && $Field.id != '').
        * Look towards the bottom of the loop for ''Normal case''.
        *
        * The rest of this deals with a 'group' within a 'group' this is more complicated,
        * these appear to smarty as an array, loop through it in the same way as the outer loop
        * works, looking for arrays with a member 'id'. Thus you end up with 3 nested loops.
        *
        * The {foreach gets the key, more by way of interest than need.
        *
        * If $FormData.debug is true then generate some tracing.
        *
        * Not everything has a label, so generate &nbsp; to keep the columns aligned.
        *
        * This generates far too many blank lines in the HTML - but this is demo code!
        *}
        {foreach from=$FormData.elements item=Field key=Key}
            {* Check that it is an input field *}
            {if is_array($Field) && $Field.id != '' && $Field.name !== 'submit_buttons'}

                {*<debug>*}{if $FormData.debug}<br>outer:id={$Field.id} key={$Key}<br>{/if}{*</debug>*}
                {if is_array($Field) && is_array($Field.elements) && $Field.id !== ''}

                    {* This is a group - loop through the subvalues *}
                    {*<debug>*}{if $FormData.debug}Group subvalues<br>{/if}{*</debug>*}
                    {if !empty($Field.label)}
                        <label class="mt20" {if $Field.error} style='color:red;'{/if}>{if $Field.required}* {/if}{$Field.label|default:'&nbsp;'}</label>
                        {*<span class="fTitle" {if $Field.error} style='color:red;'{/if}>{if $Field.required}* {/if}{$Field.label|default:'&nbsp;'}</span>*}
                    {/if}
                    {foreach from=$Field.elements item=FieldIn_1 key=KeyIn_1}
                        {* Loop through the members of the group array *}
                        {*<debug>*}{if $FormData.debug}KeyIn_1:{$KeyIn_1}<br>{/if}{*</debug>*}

                        {* Is this a group within a group ? *}
                        {if is_array($FieldIn_1) && $FieldIn_1.id !== '' && $KeyIn_1 !== 'attribs'}
                            {if is_array($FieldIn_1.elements)}
                                {foreach from=$FieldIn_1 item=FieldIn_2 key=KeyIn_2}
                                    {* 3rd nested loop - traverse group within group *}
                                    {*<debug>*}{if $FormData.debug}KeyIn_2:{$KeyIn_2}{/if}{*</debug>*}
                                    {if is_array($FieldIn_2) && $FieldIn_2.id != ''}
                                        {*<debug>*}{if $FormData.debug}Name={$FieldIn_2.name}{/if}{*</debug>*}
                                        {if !empty($FieldIn_2.label)}
                                            <div class="clear"></div>
                                            <span class="fTitle" {if $FieldIn_2.error} style='color:red;'{/if}>{if $FieldIn_2.required}* {/if}{$FieldIn_2.label|default:'&nbsp;'}</span>
                                        {/if}
                                        {if $FieldIn_2.error}<div style='color:red;'>{$FieldIn_2.error}</div>{/if}
                                        <div class="form_element_wrapper">
                                        {$FieldIn_2.html}
                                        </div>
                                    {/if}
                                {/foreach}
                            {else}
                                {* Top level group - ie not a group within a group *}
                                {*<debug>*}{if $FormData.debug}inner id: {$FieldIn_1.id} name: {$FieldIn_1.name}<br>{/if}{*</debug>*}
                                {if !empty($FieldIn_1.label)}
                                    <div class="clear"></div>
                                    <span class="fTitle" {if $FieldIn_1.error} style='color:red;'{/if}>{if $FieldIn_1.required}* {/if}{$FieldIn_1.label|default:'&nbsp;'}</span>
                                {/if}
                                {if $FieldIn_1.error}<div style='color:red;'>{$FieldIn_1.error}</div>{/if}
                                <div class="form_element_wrapper">
                                {$FieldIn_1.html}
                                </div>
                            {/if}
                        {else}
                            {*<debug>*}{if $FormData.debug}Ignore this inner field:{$FieldIn_1}{/if}{*</debug>*}
                        {/if}
                        {*<debug>*}{if $FormData.debug}<p>{/if}{*</debug>*}
                    {/foreach}

                {else}{* group check *}
                    {* Normal case - ie when not a group -- not much to this really! *}
                    <div class="clear"></div>
                    <span class="fTitle" {if $Field.error} style='color:red;'{/if}>{if $Field.required}* {/if}{$Field.label|default:'&nbsp;'}</span>

                    {if $Field.error}<div style='color:red;'>{$Field.error}</div>{/if}

                    <div class="form_element_wrapper">
                    {$Field.html}
                    </div>
                {/if}{* group check *}
            {/if}{* Input field check *}

        {/foreach}
       </td>
      </tr>
      <tr>
        <td></td>
        <td></td>
      </tr>
   </table>


{foreach from=$FormData item=Field key=Key}
    {* Check that it is an input field *}
    {if is_array($Field) && $Field.id != '' && $Key == 'submit_buttons'}
        {if is_array($Field.elements)}
          <div class="submit">

            <div style="padding-left:19px;padding-top:10px;padding-right:7px;">
                {foreach from=$Field.elements item=elem}
                    {$elem.html}
                {/foreach}
            </div>

            <div class="hide" id="warn_delete" style="margin-top:20px;margin-left:20px;" style="display: none;">
                <div class="submit">
                    <div class="warn-bx" id="warning">
                        <strong>Warning!</strong><br/>
                        Do you really want to delete this entry?
                        <div style="padding-top: 10px;">
                            {*<input type="submit" name="delete" value="Yes" />*}
                            <input type="submit" onclick="$('#warn_delete').hide();return false;" value="No" name="fSubmit" />
                        </div>
                    </div>
                </div>
            </div>

          </div>
        {/if}
    {/if}{* Input field check *}
{/foreach}

 </form>

{if isset($FormData.javascript)}
    {$FormData.javascript}
{/if}
